In [1]:
import pandas as pd
from trueskill import Rating, quality_1vs1, rate_1vs1, quality, rate, global_env, choose_backend,  backends, setup
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [14]:
df = pd.read_csv('Data/Competition.csv').drop_duplicates()
df

,division,compID,location,date,college,first_name,last_name,position,result,score
0,DII,790,"Huntington Beach, Ca",2018-02-15,Concordia,Kersti,Whitney,1,1,"15-21, 24-22, 15-13"
1,DII,790,"Huntington Beach, Ca",2018-02-15,Concordia,Avery,Keathley,1,1,"15-21, 24-22, 15-13"
2,NAIA,790,"Huntington Beach, Ca",2018-02-15,Vanguard,Kayla,Tinker,1,0,"15-21, 24-22, 15-13"
3,NAIA,790,"Huntington Beach, Ca",2018-02-15,Vanguard,Gabby,Morrison,1,0,"15-21, 24-22, 15-13"
4,DII,790,"Huntington Beach, Ca",2018-02-15,Concordia,Vanessa,Bernzen,2,1,"14-21, 21-19, 15-13"
5,DII,790,"Huntington Beach, Ca",2018-02-15,Concordia,Tristan,Self,2,1,"14-21, 21-19, 15-13"
6,NAIA,790,"Huntington Beach, Ca",2018-02-15,Vanguard,Hannah,Holder,2,0,"14-21, 21-19, 15-13"
7,NAIA,790,"Huntington Beach, Ca",2018-02-15,Vanguard,Kelli,Dowell,2,0,"14-21, 21-19, 15-13"
8,DII,790,"Huntington Beach, Ca",2018-02-15,Concordia,Kyra,Auten,3,1,"21-13, 21-13"
9,DII,790,"Huntington Beach, Ca",2018-02-15,Concordia,Marcela,Frazzoni,3,1,"21-13, 21-13"
10,NAIA,790,"Huntington Beach, Ca",2018-02-15,Vanguard,Dani,Erdelatz,3,0,"21-13, 21-13"
11,NAIA,790,"Huntington Beach, Ca",2018-02-15,Vanguard,Charity,Dennis,3,0,"21-13, 21-13"
12,DII,790,"Huntington Beach, Ca",2018-02-15,Concordia,Jessica,Diederich,4,1,"21-17, 21-10"
13,DII,790,"Huntington Beach, Ca",2018-02-15,Concordia,Asia,O'Neil,4,1,"21-17, 21-10"
14,NAIA,790,"Huntington Beach, Ca",2018-02-15,Vanguard,Eliana,Johnson,4,0,"21-17, 21-10"
15,NAIA,790,"Huntington Beach, Ca",2018-02-15,Vanguard,Karly,Cantu,4,0,"21-17, 21-10"
16,DII,790,"Huntington Beach, Ca",2018-02-15,Concordia,Kekela,Hendrickson,5,1,"21-11, 21-13"
17,DII,790,"Huntington Beach, Ca",2018-02-15,Concordia,Riley,Gill,5,1,"21-11, 21-13"
18,NAIA,790,"Huntington Beach, Ca",2018-02-15,Vanguard,Bree,Bolton,5,0,"21-11, 21-13"
19,NAIA,790,"Huntington Beach, Ca",2018-02-15,Vanguard,Karli,Burk,5,0,"21-11, 21-13"
20,DII,799,"Deland, FL",2018-02-23,Eckerd,Mackenzie,Redner,1,0,"21-12, 21-15"
21,DII,799,"Deland, FL",2018-02-23,Eckerd,Savanna,Cary,1,0,"21-12, 21-15"
22,DI,799,"Deland, FL",2018-02-23,Stetson,Carly,Perales,1,1,"21-12, 21-15"
23,DI,799,"Deland, FL",2018-02-23,Stetson,Sunniva,Helland-Hansen,1,1,"21-12, 21-15"
24,DII,799,"Deland, FL",2018-02-23,Eckerd,Paula,Hoffman,2,0,"21-18, 21-16"
25,DII,799,"Deland, FL",2018-02-23,Eckerd,Kaitlyn,Sibson,2,0,"21-18, 21-16"
26,DI,799,"Deland, FL",2018-02-23,Stetson,Sammee,Thomas,2,1,"21-18, 21-16"
27,DI,799,"Deland, FL",2018-02-23,Stetson,Darby,Dunn,2,1,"21-18, 21-16"
28,DII,799,"Deland, FL",2018-02-23,Eckerd,Madison,Whiting,3,0,"21-17, 21-17"
29,DII,799,"Deland, FL",2018-02-23,Eckerd,Arielle,Erillo,3,0,"21-17, 21-17"
...,...,...,...,...,...,...,...,...,...,...
17872,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Lily,Justine,2,1,"21-18, 21-19"
17873,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Sarah,Sponcil,2,1,"21-18, 21-19"
17874,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Sara,Putt,3,0,"21-19, 21-9"
17875,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Macy,Jerger,3,0,"21-19, 21-9"
17876,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Zana,Muno,3,1,"21-19, 21-9"
17877,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Savvy,Simo,3,1,"21-19, 21-9"
17878,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Brooke,Kuhlman,4,1,"21-15, 19-21, 15-12"
17879,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Molly,McBain,4,1,"21-15, 19-21, 15-12"
17880,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Elise,Zappia,4,0,"21-15, 19-21, 15-12"
17881,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Mac,May,4,0,"21-15, 19-21, 15-12"
17882,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Madison,Fitzpatrick,5,0,"17-21, 24-22, 15-8"
17883,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Francesca,Goncalves,5,0,"17-21, 24-22, 15-8"
17884,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Megan,Muret,5,1,"17-21, 24-22, 15-8"
17885,DI,1872,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Izzy,Carey,5,1,"17-21, 24-22, 15-8"
17886,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Katie,Horton,2,0,"21-18, 21-19"
17887,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Hailey,Luke,2,0,"21-18, 21-19"
17888,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Sarah,Sponcil,2,1,"21-18, 21-19"
17889,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Lily,Justine,2,1,"21-18, 21-19"
17890,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Macy,Jerger,3,0,"21-19, 21-9"
17891,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Sara,Putt,3,0,"21-19, 21-9"
17892,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Savvy,Simo,3,1,"21-19, 21-9"
17893,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Zana,Muno,3,1,"21-19, 21-9"
17894,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Molly,McBain,4,1,"21-15, 19-21, 15-12"
17895,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Brooke,Kuhlman,4,1,"21-15, 19-21, 15-12"
17896,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Mac,May,4,0,"21-15, 19-21, 15-12"
17897,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Elise,Zappia,4,0,"21-15, 19-21, 15-12"
17898,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Francesca,Goncalves,5,0,"17-21, 24-22, 15-8"
17899,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,Florida State,Madison,Fitzpatrick,5,0,"17-21, 24-22, 15-8"
17900,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Megan,Muret,5,1,"17-21, 24-22, 15-8"
17901,DI,1873,"Gulf Shores, Al (NCAA Championship)",2018-05-06,UCLA,Izzy,Carey,5,1,"17-21, 24-22, 15-8"

In [3]:
sort_order = ['date', 'compID', 'position', 'result','last_name', 'first_name']

In [5]:
def get_competition_info(df, div):  
    df = get_teams_by_division(df, div)                                                      ## Get D1 Teams
    df = strip_all_strings_in_df(df, ['first_name', 'last_name', 'college', 'location', 'division', 'score'])     ##strip whitespace
    df = df.groupby('compID').filter(lambda x: len(x) == 20)                                 ## Remove matches against community colleges                                                 ## set default player rating
    return df.sort_values(['date', 'compID', 'position', 'result'], ascending=True).reset_index().iloc[:,1:]

def get_teams_by_division(df, div):
    df = df[df["division"] == div] \
                    .drop_duplicates() \
                    .reset_index() \
                    .iloc[:,1:]
    return df.sort_values(sort_order, ascending=True)

def strip_all_strings_in_df(df, cols):
    for s in cols:
        df[s] = df[s].apply(lambda x: x.strip())
    return df

def set_player_ratings_after_match(df,i, new):
    idx = df_player[(df_player.first_name == df.iloc[i, 0]) \
                 & (df_player.last_name == df.iloc[i, 1]) \
                 & (df_player.college == df.iloc[i, 2])].index
    df_player.loc[idx, 'rating'] = new
    return None

In [6]:
df_matches = get_competition_info(df, 'DI')
df_matches

,division,compID,location,date,college,first_name,last_name,position,result,score
0,DI,800,"Deland, FL",2018-02-23,Georgia State,Tiffany,Creamer,1,0,"22-24, 21-17, 15-13"
1,DI,800,"Deland, FL",2018-02-23,Georgia State,Brooke,Weiner,1,0,"22-24, 21-17, 15-13"
2,DI,800,"Deland, FL",2018-02-23,South Carolina,Ali,Denney,1,1,"22-24, 21-17, 15-13"
3,DI,800,"Deland, FL",2018-02-23,South Carolina,Shannon,Williams,1,1,"22-24, 21-17, 15-13"
4,DI,800,"Deland, FL",2018-02-23,Georgia State,Allie,Elson,2,0,"21-18, 21-14"
5,DI,800,"Deland, FL",2018-02-23,Georgia State,Ashley,McGinn,2,0,"21-18, 21-14"
6,DI,800,"Deland, FL",2018-02-23,South Carolina,Lydia,Dimke,2,1,"21-18, 21-14"
7,DI,800,"Deland, FL",2018-02-23,South Carolina,Katie,Smith,2,1,"21-18, 21-14"
8,DI,800,"Deland, FL",2018-02-23,Georgia State,Eden,Hawes,3,0,"21-16, 21-11"
9,DI,800,"Deland, FL",2018-02-23,Georgia State,Georgia,Johnson,3,0,"21-16, 21-11"
10,DI,800,"Deland, FL",2018-02-23,South Carolina,Julia,Mannisto,3,1,"21-16, 21-11"
11,DI,800,"Deland, FL",2018-02-23,South Carolina,Carly,Schneider,3,1,"21-16, 21-11"
12,DI,800,"Deland, FL",2018-02-23,Georgia State,Rebekah,Brodbeck,4,0,"21-12, 21-15"
13,DI,800,"Deland, FL",2018-02-23,Georgia State,Kate,Novack,4,0,"21-12, 21-15"
14,DI,800,"Deland, FL",2018-02-23,South Carolina,Leah,Perri,4,1,"21-12, 21-15"
15,DI,800,"Deland, FL",2018-02-23,South Carolina,Macie,Tendrich,4,1,"21-12, 21-15"
16,DI,800,"Deland, FL",2018-02-23,Georgia State,Maddie,Gordon,5,0,"21-15, 21-19"
17,DI,800,"Deland, FL",2018-02-23,Georgia State,Amie,Held,5,0,"21-15, 21-19"
18,DI,800,"Deland, FL",2018-02-23,South Carolina,Hannah,Edelman,5,1,"21-15, 21-19"
19,DI,800,"Deland, FL",2018-02-23,South Carolina,Franky,Harrison,5,1,"21-15, 21-19"
20,DI,801,"Deland, FL",2018-02-23,FAU,Gabrielle,Dischler,1,0,"12-21, 21-17, 15-6"
21,DI,801,"Deland, FL",2018-02-23,FAU,Jessalyn,Kinlaw,1,0,"12-21, 21-17, 15-6"
22,DI,801,"Deland, FL",2018-02-23,Florida State,Macy,Jerger,1,1,"12-21, 21-17, 15-6"
23,DI,801,"Deland, FL",2018-02-23,Florida State,Victoria,Paranagua,1,1,"12-21, 21-17, 15-6"
24,DI,801,"Deland, FL",2018-02-23,FAU,Brittany,Pellitteri,2,0,"21-16, 23-21"
25,DI,801,"Deland, FL",2018-02-23,FAU,Carly,Scarborough,2,0,"21-16, 23-21"
26,DI,801,"Deland, FL",2018-02-23,Florida State,Vanessa,Freire,2,1,"21-16, 23-21"
27,DI,801,"Deland, FL",2018-02-23,Florida State,Brooke,Kuhlman,2,1,"21-16, 23-21"
28,DI,801,"Deland, FL",2018-02-23,FAU,Nicole,Grant,3,0,"21-16, 21-19"
29,DI,801,"Deland, FL",2018-02-23,FAU,Nicole,Navarro,3,0,"21-16, 21-19"
...,...,...,...,...,...,...,...,...,...,...
12830,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Carly,Kan,3,1,"17-21, 21-19, 15-11"
12831,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Laurel,Weaver,3,1,"17-21, 21-19, 15-11"
12832,DI,1869,"Gulf Shores, Al",2018-05-05,Florida State,Brooke,Kuhlman,4,0,"22-20, 21-16"
12833,DI,1869,"Gulf Shores, Al",2018-05-05,Florida State,Molly,McBain,4,0,"22-20, 21-16"
12834,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Ari,Homayun,4,1,"22-20, 21-16"
12835,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Amy,Ozee,4,1,"22-20, 21-16"
12836,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Paige,Dreeuws,5,0,"24-22, 21-23, 15-12"
12837,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Hannah,Zalopany,5,0,"24-22, 21-23, 15-12"
12838,DI,1869,"Gulf Shores, Al",2018-05-05,Florida State,Madison,Fitzpatrick,5,1,"24-22, 21-23, 15-12"
12839,DI,1869,"Gulf Shores, Al",2018-05-05,Florida State,Francesca,Goncalves,5,1,"24-22, 21-23, 15-12"
12840,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Emily,Maglio,1,0,"22-20, 21-18"
12841,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Ka'iwi,Schucht,1,0,"22-20, 21-18"
12842,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Megan,McNamara,1,1,"22-20, 21-18"
12843,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Nicole,McNamara,1,1,"22-20, 21-18"
12844,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Morgan,Martin,2,0,"21-19, 23-25, 15-11"
12845,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Lea,Monkhouse,2,0,"21-19, 23-25, 15-11"
12846,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Lily,Justine,2,1,"21-19, 23-25, 15-11"
12847,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Sarah,Sponcil,2,1,"21-19, 23-25, 15-11"
12848,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Zana,Muno,3,0,"21-19, 16-21, 15-12"
12849,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Savvy,Simo,3,0,"21-19, 16-21, 15-12"
12850,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Carly,Kan,3,1,"21-19, 16-21, 15-12"
12851,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Laurel,Weaver,3,1,"21-19, 16-21, 15-12"
12852,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Mac,May,4,0,"21-16, 21-16"
12853,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Elise,Zappia,4,0,"21-16, 21-16"
12854,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Ari,Homayun,4,1,"21-16, 21-16"
12855,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Amy,Ozee,4,1,"21-16, 21-16"
12856,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Paige,Dreeuws,5,0,"21-14, 21-12"
12857,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Hannah,Zalopany,5,0,"21-14, 21-12"
12858,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Izzy,Carey,5,1,"21-14, 21-12"
12859,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Megan,Muret,5,1,"21-14, 21-12"

In [7]:
def set_default_player_rating(df_match_, division='DI'): 
    df_players_ = df_match_.loc[:, ['division',  'college', 'first_name', 'last_name', 'mu', 'sigma']].copy()
    df_players_ = strip_all_strings_in_df(df_players_, ['division',  'college', 'first_name', 'last_name'])
    df_players_ = df_players_.drop_duplicates()
    df_players_ = df_players_[df_players_.division == division]
    df_players_['mu'] = Rating().mu
    df_players_['sigma'] = Rating().sigma
    df_players_ = df_players_.sort_values(['last_name', 'first_name', 'college'], ascending=True)
    df_players_ = df_players_.reset_index()
    df_players_ = df_players_.loc[:, ['division',  'college', 'first_name', 'last_name',  'mu', 'sigma']]
    return df_players_

df_players = set_default_player_rating(df, 'DI')
df_players.head(5)

/usr/local/anaconda3/envs/Conda3/lib/python2.7/site-packages/pandas/core/indexing.py:1472: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

  division           college first_name   last_name    mu     sigma
0       DI      Jacksonville    Forfeit           1  25.0  8.333333
1       DI       Santa Clara    Forfeit           1  25.0  8.333333
2       DI      Jacksonville    Forfeit           2  25.0  8.333333
3       DI       Santa Clara    Forfeit           2  25.0  8.333333
4       DI  Long Beach State   Kristyna  Adamcikova  25.0  8.333333

In [20]:
df_matches[0:400]

,division,compID,location,date,college,first_name,last_name,position,result,score
0,DI,800,"Deland, FL",2018-02-23,Georgia State,Tiffany,Creamer,1,0,"22-24, 21-17, 15-13"
1,DI,800,"Deland, FL",2018-02-23,Georgia State,Brooke,Weiner,1,0,"22-24, 21-17, 15-13"
2,DI,800,"Deland, FL",2018-02-23,South Carolina,Ali,Denney,1,1,"22-24, 21-17, 15-13"
3,DI,800,"Deland, FL",2018-02-23,South Carolina,Shannon,Williams,1,1,"22-24, 21-17, 15-13"
4,DI,800,"Deland, FL",2018-02-23,Georgia State,Allie,Elson,2,0,"21-18, 21-14"
5,DI,800,"Deland, FL",2018-02-23,Georgia State,Ashley,McGinn,2,0,"21-18, 21-14"
6,DI,800,"Deland, FL",2018-02-23,South Carolina,Lydia,Dimke,2,1,"21-18, 21-14"
7,DI,800,"Deland, FL",2018-02-23,South Carolina,Katie,Smith,2,1,"21-18, 21-14"
8,DI,800,"Deland, FL",2018-02-23,Georgia State,Eden,Hawes,3,0,"21-16, 21-11"
9,DI,800,"Deland, FL",2018-02-23,Georgia State,Georgia,Johnson,3,0,"21-16, 21-11"
10,DI,800,"Deland, FL",2018-02-23,South Carolina,Julia,Mannisto,3,1,"21-16, 21-11"
11,DI,800,"Deland, FL",2018-02-23,South Carolina,Carly,Schneider,3,1,"21-16, 21-11"
12,DI,800,"Deland, FL",2018-02-23,Georgia State,Rebekah,Brodbeck,4,0,"21-12, 21-15"
13,DI,800,"Deland, FL",2018-02-23,Georgia State,Kate,Novack,4,0,"21-12, 21-15"
14,DI,800,"Deland, FL",2018-02-23,South Carolina,Leah,Perri,4,1,"21-12, 21-15"
15,DI,800,"Deland, FL",2018-02-23,South Carolina,Macie,Tendrich,4,1,"21-12, 21-15"
16,DI,800,"Deland, FL",2018-02-23,Georgia State,Maddie,Gordon,5,0,"21-15, 21-19"
17,DI,800,"Deland, FL",2018-02-23,Georgia State,Amie,Held,5,0,"21-15, 21-19"
18,DI,800,"Deland, FL",2018-02-23,South Carolina,Hannah,Edelman,5,1,"21-15, 21-19"
19,DI,800,"Deland, FL",2018-02-23,South Carolina,Franky,Harrison,5,1,"21-15, 21-19"
20,DI,801,"Deland, FL",2018-02-23,FAU,Gabrielle,Dischler,1,0,"12-21, 21-17, 15-6"
21,DI,801,"Deland, FL",2018-02-23,FAU,Jessalyn,Kinlaw,1,0,"12-21, 21-17, 15-6"
22,DI,801,"Deland, FL",2018-02-23,Florida State,Macy,Jerger,1,1,"12-21, 21-17, 15-6"
23,DI,801,"Deland, FL",2018-02-23,Florida State,Victoria,Paranagua,1,1,"12-21, 21-17, 15-6"
24,DI,801,"Deland, FL",2018-02-23,FAU,Brittany,Pellitteri,2,0,"21-16, 23-21"
25,DI,801,"Deland, FL",2018-02-23,FAU,Carly,Scarborough,2,0,"21-16, 23-21"
26,DI,801,"Deland, FL",2018-02-23,Florida State,Vanessa,Freire,2,1,"21-16, 23-21"
27,DI,801,"Deland, FL",2018-02-23,Florida State,Brooke,Kuhlman,2,1,"21-16, 23-21"
28,DI,801,"Deland, FL",2018-02-23,FAU,Nicole,Grant,3,0,"21-16, 21-19"
29,DI,801,"Deland, FL",2018-02-23,FAU,Nicole,Navarro,3,0,"21-16, 21-19"
...,...,...,...,...,...,...,...,...,...,...
370,DI,836,"Stockton, Ca",2018-02-24,Cal,Alexia,Inman,3,1,"21-13, 21-8"
371,DI,836,"Stockton, Ca",2018-02-24,Cal,Mima,Mirkovic,3,1,"21-13, 21-8"
372,DI,836,"Stockton, Ca",2018-02-24,Pacific,Ashlyn,Fleming,4,0,"21-11, 21-16"
373,DI,836,"Stockton, Ca",2018-02-24,Pacific,Kaitlyn,Lines,4,0,"21-11, 21-16"
374,DI,836,"Stockton, Ca",2018-02-24,Cal,Maddie,Micheletti,4,1,"21-11, 21-16"
375,DI,836,"Stockton, Ca",2018-02-24,Cal,Caroline,Schafer,4,1,"21-11, 21-16"
376,DI,836,"Stockton, Ca",2018-02-24,Cal,Grace,Campbell,5,0,"21-18, 21-15"
377,DI,836,"Stockton, Ca",2018-02-24,Cal,Mia,Merino,5,0,"21-18, 21-15"
378,DI,836,"Stockton, Ca",2018-02-24,Pacific,Katrin,Gotterba,5,1,"21-18, 21-15"
379,DI,836,"Stockton, Ca",2018-02-24,Pacific,Alex,Holt,5,1,"21-18, 21-15"
380,DI,837,"Honolulu, Hi",2018-02-24,Stanford,Kathryn,Plummer,1,0,"21-19, 21-18"
381,DI,837,"Honolulu, Hi",2018-02-24,Stanford,Sunny,Villapando,1,0,"21-19, 21-18"
382,DI,837,"Honolulu, Hi",2018-02-24,Hawaii,Carly,Kan,1,1,"21-19, 21-18"
383,DI,837,"Honolulu, Hi",2018-02-24,Hawaii,Laurel,Weaver,1,1,"21-19, 21-18"
384,DI,837,"Honolulu, Hi",2018-02-24,Stanford,Morgan,Hentz,2,0,"18-21, 21-13, 15-7"
385,DI,837,"Honolulu, Hi",2018-02-24,Stanford,Amelia,Smith,2,0,"18-21, 21-13, 15-7"
386,DI,837,"Honolulu, Hi",2018-02-24,Hawaii,Emily,Maglio,2,1,"18-21, 21-13, 15-7"
387,DI,837,"Honolulu, Hi",2018-02-24,Hawaii,Ka'iwi,Schucht,2,1,"18-21, 21-13, 15-7"
388,DI,837,"Honolulu, Hi",2018-02-24,Stanford,Payton,Chang,3,0,"21-12, 21-11"
389,DI,837,"Honolulu, Hi",2018-02-24,Stanford,Catherine,Raquel,3,0,"21-12, 21-11"
390,DI,837,"Honolulu, Hi",2018-02-24,Hawaii,Morgan,Martin,3,1,"21-12, 21-11"
391,DI,837,"Honolulu, Hi",2018-02-24,Hawaii,Lea,Monkhouse,3,1,"21-12, 21-11"
392,DI,837,"Honolulu, Hi",2018-02-24,Hawaii,Ari,Homayun,4,0,"15-21, 23-21, 16-14"
393,DI,837,"Honolulu, Hi",2018-02-24,Hawaii,Amy,Ozee,4,0,"15-21, 23-21, 16-14"
394,DI,837,"Honolulu, Hi",2018-02-24,Stanford,Courtney,Bowen,4,1,"15-21, 23-21, 16-14"
395,DI,837,"Honolulu, Hi",2018-02-24,Stanford,Kate,Formico,4,1,"15-21, 23-21, 16-14"
396,DI,837,"Honolulu, Hi",2018-02-24,Stanford,Kat,Anderson,5,0,"21-15, 21-19"
397,DI,837,"Honolulu, Hi",2018-02-24,Stanford,Caitlin,Keefe,5,0,"21-15, 21-19"
398,DI,837,"Honolulu, Hi",2018-02-24,Hawaii,Paige,Dreeuws,5,1,"21-15, 21-19"
399,DI,837,"Honolulu, Hi",2018-02-24,Hawaii,Hannah,Zalopany,5,1,"21-15, 21-19"

In [81]:
def get_player_ratings_from_match(df_players_, fname, lname, college):
    idx = df_players_[(df_players_.first_name == fname) \
                 & (df_players_.last_name == lname) \
                 & (df_players_.college == college)].index
    my_mu = df_players_.iloc[idx.item(),  df_players_.columns.get_loc('mu')]
    my_sigma = df_players_.iloc[idx.item(),  df_players_.columns.get_loc('sigma')]
    my_rating = Rating(mu=my_mu, sigma=my_sigma)
    return my_rating

def set_player_ratings_after_match(df_players_, fname, lname, college, position, rating_):
    idx = df_players_[(df_players_.first_name == fname) \
                 & (df_players_.last_name == lname) \
                 & (df_players_.college == college)].index
    df_players_.iloc[idx,  df_players_.columns.get_loc('mu')] = rating_.mu + position_factor[int(position)-1]
    df_players_.iloc[idx,  df_players_.columns.get_loc('sigma')] = rating_.sigma
    
    my_mu = df_players_.iloc[idx.item(),  df_players_.columns.get_loc('mu')]
    my_sigma = df_players_.iloc[idx.item(),  df_players_.columns.get_loc('sigma')]
    my_rating = Rating(mu=my_mu, sigma=my_sigma)
    
    return my_rating

position_factor = [.6,.3,.2,.1,.05]

df_matches = get_competition_info(df, 'DI')
df_players = set_default_player_rating(df, 'DI')

groups = df_matches.groupby(['date', 'compID', 'position']).groups

#print sorted(groups)

counter = 0
hist_dict = {}

for key, value in sorted(groups.iteritems()):
    r = {}
    r_new = {}
    #print key, len(value),
    for i in range(len(value)):
        fname = df_matches.iloc[value[i], df_matches.columns.get_loc('first_name')]
        lname = df_matches.iloc[value[i], df_matches.columns.get_loc('last_name')]
        college = df_matches.iloc[value[i], df_matches.columns.get_loc('college')]
        position = df_matches.iloc[value[i], df_matches.columns.get_loc('position')]
        r[i] = get_player_ratings_from_match(df_players, fname, lname, college)

    
    t1 = [r[0], r[1]]
    t2 = [r[2], r[3]]

    ((r_new[0], r_new[1]), (r_new[2], r_new[3])) = rate([t1,t2], ranks=[1,0])

    
    for j in range(4):
        #print j, r_new[j]
        fname = df_matches.iloc[value[j], df_matches.columns.get_loc('first_name')]
        lname = df_matches.iloc[value[j], df_matches.columns.get_loc('last_name')]
        college = df_matches.iloc[value[j], df_matches.columns.get_loc('college')]
        position = df_matches.iloc[value[j], df_matches.columns.get_loc('position')]
        set_player_ratings_after_match(df_players, fname, lname, college,  position, r_new[j]) 
    
    hist_dict[counter] = df_matches.iloc[value].merge(df_players, left_on=['first_name', 'last_name', 'college'], right_on=['first_name', 'last_name', 'college'], how='inner')
    counter += 1

df_match_history = pd.concat(hist_dict.values(), axis=0)
df_match_history.sort_values(['date','compID'], ascending=True)

,division_x,compID,location,date,college,first_name,last_name,position,result,score,division_y,mu,sigma
0,DI,800,"Deland, FL",2018-02-23,Georgia State,Tiffany,Creamer,1,0,"22-24, 21-17, 15-13",DI,22.491677,7.774363
1,DI,800,"Deland, FL",2018-02-23,Georgia State,Brooke,Weiner,1,0,"22-24, 21-17, 15-13",DI,22.491677,7.774363
2,DI,800,"Deland, FL",2018-02-23,South Carolina,Ali,Denney,1,1,"22-24, 21-17, 15-13",DI,28.708323,7.774363
3,DI,800,"Deland, FL",2018-02-23,South Carolina,Shannon,Williams,1,1,"22-24, 21-17, 15-13",DI,28.708323,7.774363
0,DI,800,"Deland, FL",2018-02-23,Georgia State,Allie,Elson,2,0,"21-18, 21-14",DI,22.191677,7.774363
1,DI,800,"Deland, FL",2018-02-23,Georgia State,Ashley,McGinn,2,0,"21-18, 21-14",DI,22.191677,7.774363
2,DI,800,"Deland, FL",2018-02-23,South Carolina,Lydia,Dimke,2,1,"21-18, 21-14",DI,28.408323,7.774363
3,DI,800,"Deland, FL",2018-02-23,South Carolina,Katie,Smith,2,1,"21-18, 21-14",DI,28.408323,7.774363
0,DI,800,"Deland, FL",2018-02-23,Georgia State,Eden,Hawes,3,0,"21-16, 21-11",DI,22.091677,7.774363
1,DI,800,"Deland, FL",2018-02-23,Georgia State,Georgia,Johnson,3,0,"21-16, 21-11",DI,22.091677,7.774363
2,DI,800,"Deland, FL",2018-02-23,South Carolina,Julia,Mannisto,3,1,"21-16, 21-11",DI,28.308323,7.774363
3,DI,800,"Deland, FL",2018-02-23,South Carolina,Carly,Schneider,3,1,"21-16, 21-11",DI,28.308323,7.774363
0,DI,800,"Deland, FL",2018-02-23,Georgia State,Rebekah,Brodbeck,4,0,"21-12, 21-15",DI,21.991677,7.774363
1,DI,800,"Deland, FL",2018-02-23,Georgia State,Kate,Novack,4,0,"21-12, 21-15",DI,21.991677,7.774363
2,DI,800,"Deland, FL",2018-02-23,South Carolina,Leah,Perri,4,1,"21-12, 21-15",DI,28.208323,7.774363
3,DI,800,"Deland, FL",2018-02-23,South Carolina,Macie,Tendrich,4,1,"21-12, 21-15",DI,28.208323,7.774363
0,DI,800,"Deland, FL",2018-02-23,Georgia State,Maddie,Gordon,5,0,"21-15, 21-19",DI,21.941677,7.774363
1,DI,800,"Deland, FL",2018-02-23,Georgia State,Amie,Held,5,0,"21-15, 21-19",DI,21.941677,7.774363
2,DI,800,"Deland, FL",2018-02-23,South Carolina,Hannah,Edelman,5,1,"21-15, 21-19",DI,28.158323,7.774363
3,DI,800,"Deland, FL",2018-02-23,South Carolina,Franky,Harrison,5,1,"21-15, 21-19",DI,28.158323,7.774363
0,DI,801,"Deland, FL",2018-02-23,FAU,Gabrielle,Dischler,1,0,"12-21, 21-17, 15-6",DI,22.491677,7.774363
1,DI,801,"Deland, FL",2018-02-23,FAU,Jessalyn,Kinlaw,1,0,"12-21, 21-17, 15-6",DI,22.491677,7.774363
2,DI,801,"Deland, FL",2018-02-23,Florida State,Macy,Jerger,1,1,"12-21, 21-17, 15-6",DI,28.708323,7.774363
3,DI,801,"Deland, FL",2018-02-23,Florida State,Victoria,Paranagua,1,1,"12-21, 21-17, 15-6",DI,28.708323,7.774363
0,DI,801,"Deland, FL",2018-02-23,FAU,Brittany,Pellitteri,2,0,"21-16, 23-21",DI,22.191677,7.774363
1,DI,801,"Deland, FL",2018-02-23,FAU,Carly,Scarborough,2,0,"21-16, 23-21",DI,22.191677,7.774363
2,DI,801,"Deland, FL",2018-02-23,Florida State,Vanessa,Freire,2,1,"21-16, 23-21",DI,28.408323,7.774363
3,DI,801,"Deland, FL",2018-02-23,Florida State,Brooke,Kuhlman,2,1,"21-16, 23-21",DI,28.408323,7.774363
0,DI,801,"Deland, FL",2018-02-23,FAU,Nicole,Grant,3,0,"21-16, 21-19",DI,22.091677,7.774363
1,DI,801,"Deland, FL",2018-02-23,FAU,Nicole,Navarro,3,0,"21-16, 21-19",DI,22.091677,7.774363
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Carly,Kan,3,1,"17-21, 21-19, 15-11",DI,43.427012,2.685134
3,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Laurel,Weaver,3,1,"17-21, 21-19, 15-11",DI,42.872716,2.703328
0,DI,1869,"Gulf Shores, Al",2018-05-05,Florida State,Brooke,Kuhlman,4,0,"22-20, 21-16",DI,33.758619,2.893561
1,DI,1869,"Gulf Shores, Al",2018-05-05,Florida State,Molly,McBain,4,0,"22-20, 21-16",DI,37.917376,3.064363
2,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Ari,Homayun,4,1,"22-20, 21-16",DI,38.942064,2.901341
3,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Amy,Ozee,4,1,"22-20, 21-16",DI,38.942064,2.901341
0,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Paige,Dreeuws,5,0,"24-22, 21-23, 15-12",DI,35.453890,2.990424
1,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Hannah,Zalopany,5,0,"24-22, 21-23, 15-12",DI,36.588192,2.880844
2,DI,1869,"Gulf Shores, Al",2018-05-05,Florida State,Madison,Fitzpatrick,5,1,"24-22, 21-23, 15-12",DI,30.489550,4.197872
3,DI,1869,"Gulf Shores, Al",2018-05-05,Florida State,Francesca,Goncalves,5,1,"24-22, 21-23, 15-12",DI,38.719176,3.164927
0,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Emily,Maglio,1,0,"22-20, 21-18",DI,54.309366,3.045076
1,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Ka'iwi,Schucht,1,0,"22-20, 21-18",DI,54.309366,3.045076
2,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Megan,McNamara,1,1,"22-20, 21-18",DI,57.499653,2.828828
3,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Nicole,McNamara,1,1,"22-20, 21-18",DI,57.499653,2.828828
0,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Morgan,Martin,2,0,"21-19, 23-25, 15-11",DI,45.450571,3.010269
1,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Lea,Monkhouse,2,0,"21-19, 23-25, 15-11",DI,45.023081,3.027990
2,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Lily,Justine,2,1,"21-19, 23-25, 15-11",DI,47.471700,2.617970
3,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Sarah,Sponcil,2,1,"21-19, 23-25, 15-11",DI,47.471700,2.617970
0,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Zana,Muno,3,0,"21-19, 16-21, 15-12",DI,42.706676,3.316162
1,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Savvy,Simo,3,0,"21-19, 16-21, 15-12",DI,39.550911,2.685142
2,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Carly,Kan,3,1,"21-19, 16-21, 15-12",DI,44.102713,2.630608
3,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Laurel,Weaver,3,1,"21-19, 16-21, 15-12",DI,43.554878,2.647644
0,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Mac,May,4,0,"21-16, 21-16",DI,34.998356,2.761986
1,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Elise,Zappia,4,0,"21-16, 21-16",DI,39.064639,2.611037
2,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Ari,Homayun,4,1,"21-16, 21-16",DI,39.609705,2.830246
3,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Amy,Ozee,4,1,"21-16, 21-16",DI,39.609705,2.830246
0,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Paige,Dreeuws,5,0,"21-14, 21-12",DI,34.881859,2.912257
1,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Hannah,Zalopany,5,0,"21-14, 21-12",DI,36.060878,2.811189
2,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Izzy,Carey,5,1,"21-14, 21-12",DI,37.919368,2.795751
3,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Megan,Muret,5,1,"21-14, 21-12",DI,37.919368,2.795751

In [82]:
df_players.sort_values('mu', ascending=False)

,division,college,first_name,last_name,mu,sigma
85,DI,USC,Abril,Bustamante,59.800488,3.104487
234,DI,USC,Tina,Graudina,58.865957,3.406198
418,DI,UCLA,Nicole,McNamara,57.499653,2.828828
417,DI,UCLA,Megan,McNamara,57.499653,2.828828
489,DI,Florida State,Victoria,Paranagua,57.247898,2.676767
383,DI,Hawaii,Emily,Maglio,54.309366,3.045076
580,DI,Hawaii,Ka'iwi,Schucht,54.309366,3.045076
117,DI,LSU,Claire,Coppola,53.149023,2.847302
471,DI,LSU,Kristen,Nuss,53.149023,2.847302
317,DI,Long Beach State,Sasha,Karelov,51.303704,3.124695
36,DI,Long Beach State,Nele,Barber,51.017768,3.041378
663,DI,Stanford,Sunny,Villapando,50.479668,3.158076
519,DI,Pepperdine,Corinne,Quiggle,50.453778,3.205103
339,DI,Pepperdine,Deahna,Kraft,50.453778,3.205103
429,DI,Tulane,Madeline,Mertz,50.267863,3.018476
421,DI,Tulane,Kaylie,Mchugh,50.267863,3.018476
202,DI,Florida State,Vanessa,Freire,48.973396,2.644764
697,DI,Houston Baptist,Jessica,Wooten,48.073204,3.359193
282,DI,Houston Baptist,Aeriel,Horton,48.073204,3.359193
652,DI,Georgia State,Teegan,Van Gunst,47.900252,2.757585
606,DI,South Carolina,Katie,Smith,47.871944,3.086166
57,DI,FIU,Margherita,Bianchin,47.811641,3.234273
199,DI,FIU,Federica,Frasca,47.811641,3.234273
313,DI,UCLA,Lily,Justine,47.471700,2.617970
611,DI,UCLA,Sarah,Sponcil,47.471700,2.617970
438,DI,Cal,Mima,Mirkovic,47.269680,2.954288
283,DI,Florida State,Katie,Horton,47.149979,3.392235
376,DI,Florida State,Hailey,Luke,46.832517,3.397129
247,DI,USC,Haley,Hallgren,46.322830,2.339247
13,DI,Utah,Adore,Anae,46.292643,3.951189
...,...,...,...,...,...,...
554,DI,Morehead State,Lauren,Rokey,15.534828,6.847360
159,DI,Utah,Brianna,Doehrmann,15.524486,4.765270
407,DI,Morehead State,Danielle,McCarson,15.513342,6.525380
185,DI,Morehead State,Maddie,Fella,15.513342,6.525380
111,DI,USF,Pi'ikea,Clemens,15.473802,4.934174
270,DI,Cal State Bakersfield,Krista,Hernandez,15.327286,4.666091
563,DI,Jacksonville,Bethany,Salapek,15.202477,5.630039
530,DI,Santa Clara,Gretchen,Reinert,15.066933,5.092608
150,DI,Nebraska,Hayley,Densberger,15.043974,5.727704
391,DI,Jacksonville,Hannah,Marchand,14.948148,5.684534
680,DI,Abilene Christian,Amy,Weiss,14.729050,5.011657
425,DI,"Cal State University, Sacramento",Hannah,Meadows,14.552841,4.432298
583,DI,Portland,McKenzie,Schwan,14.540670,5.158073
685,DI,Cal State Bakersfield,Sydney,Wicks,14.501568,5.832226
146,DI,Missouri State,Sarah,Demmer,14.491453,5.184901
603,DI,ULM,Bailey,Smith,14.308060,3.810453
670,DI,Abilene Christian,Lauren,Walker,14.151977,5.246037
544,DI,Abilene Christian,Brooke,Riley,14.151977,5.246037
35,DI,Cal State Bakersfield,Ally,Barber,14.081384,4.364803
300,DI,Jacksonville State,Grace,Jarnagin,13.522702,4.240763
184,DI,"Cal State University, Sacramento",Sarah,Falk,13.333447,5.885924
534,DI,Jacksonville,Tori,Reiser,13.290918,5.673712
358,DI,USF,Shannon,Levinson,13.038751,4.685071
310,DI,Morehead State,Jordan,Jones,13.034572,6.331013
643,DI,Coastal Carolina,Aristea,Tontai,12.890314,5.501876
178,DI,Coastal Carolina,Kalin,Eske,12.890314,5.501876
122,DI,Abilene Christian,Paris,Cosley,12.740941,5.697874
454,DI,Portland,Lauren,Naatz,12.011893,4.797137
537,DI,Abilene Christian,Sofia,Resendiz,11.693863,5.525112
113,DI,Jacksonville State,Maddie,Cloutier,6.503653,4.185376

In [83]:
df_match_history[df_match_history['college'].isin(['USC', 'UCLA', 'Hawaii', 'LSU', 'Florida State', 'Tulane', 'FIU', 'Cal Poly SLO', 'Pepperdine', 'South Carolina'])].sort_values(['date', 'compID', 'position', 'result'], ascending=False)

,division_x,compID,location,date,college,first_name,last_name,position,result,score,division_y,mu,sigma
2,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Izzy,Carey,5,1,"21-14, 21-12",DI,37.919368,2.795751
3,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Megan,Muret,5,1,"21-14, 21-12",DI,37.919368,2.795751
0,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Paige,Dreeuws,5,0,"21-14, 21-12",DI,34.881859,2.912257
1,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Hannah,Zalopany,5,0,"21-14, 21-12",DI,36.060878,2.811189
2,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Ari,Homayun,4,1,"21-16, 21-16",DI,39.609705,2.830246
3,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Amy,Ozee,4,1,"21-16, 21-16",DI,39.609705,2.830246
0,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Mac,May,4,0,"21-16, 21-16",DI,34.998356,2.761986
1,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Elise,Zappia,4,0,"21-16, 21-16",DI,39.064639,2.611037
2,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Carly,Kan,3,1,"21-19, 16-21, 15-12",DI,44.102713,2.630608
3,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Laurel,Weaver,3,1,"21-19, 16-21, 15-12",DI,43.554878,2.647644
0,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Zana,Muno,3,0,"21-19, 16-21, 15-12",DI,42.706676,3.316162
1,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Savvy,Simo,3,0,"21-19, 16-21, 15-12",DI,39.550911,2.685142
2,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Lily,Justine,2,1,"21-19, 23-25, 15-11",DI,47.471700,2.617970
3,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Sarah,Sponcil,2,1,"21-19, 23-25, 15-11",DI,47.471700,2.617970
0,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Morgan,Martin,2,0,"21-19, 23-25, 15-11",DI,45.450571,3.010269
1,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Lea,Monkhouse,2,0,"21-19, 23-25, 15-11",DI,45.023081,3.027990
2,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Megan,McNamara,1,1,"22-20, 21-18",DI,57.499653,2.828828
3,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,UCLA,Nicole,McNamara,1,1,"22-20, 21-18",DI,57.499653,2.828828
0,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Emily,Maglio,1,0,"22-20, 21-18",DI,54.309366,3.045076
1,DI,1871,"Gulf Shores, Al (NCAA Semis)",2018-05-06,Hawaii,Ka'iwi,Schucht,1,0,"22-20, 21-18",DI,54.309366,3.045076
2,DI,1869,"Gulf Shores, Al",2018-05-05,Florida State,Madison,Fitzpatrick,5,1,"24-22, 21-23, 15-12",DI,30.489550,4.197872
3,DI,1869,"Gulf Shores, Al",2018-05-05,Florida State,Francesca,Goncalves,5,1,"24-22, 21-23, 15-12",DI,38.719176,3.164927
0,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Paige,Dreeuws,5,0,"24-22, 21-23, 15-12",DI,35.453890,2.990424
1,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Hannah,Zalopany,5,0,"24-22, 21-23, 15-12",DI,36.588192,2.880844
2,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Ari,Homayun,4,1,"22-20, 21-16",DI,38.942064,2.901341
3,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Amy,Ozee,4,1,"22-20, 21-16",DI,38.942064,2.901341
0,DI,1869,"Gulf Shores, Al",2018-05-05,Florida State,Brooke,Kuhlman,4,0,"22-20, 21-16",DI,33.758619,2.893561
1,DI,1869,"Gulf Shores, Al",2018-05-05,Florida State,Molly,McBain,4,0,"22-20, 21-16",DI,37.917376,3.064363
2,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Carly,Kan,3,1,"17-21, 21-19, 15-11",DI,43.427012,2.685134
3,DI,1869,"Gulf Shores, Al",2018-05-05,Hawaii,Laurel,Weaver,3,1,"17-21, 21-19, 15-11",DI,42.872716,2.703328
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,DI,803,"Deland, FL",2018-02-23,South Carolina,Leah,Perri,3,0,"21-14, 21-15",DI,25.568866,7.269963
1,DI,803,"Deland, FL",2018-02-23,South Carolina,Macie,Tendrich,3,0,"21-14, 21-15",DI,25.568866,7.269963
2,DI,803,"Deland, FL",2018-02-23,South Carolina,Carly,Schneider,2,1,"24-26, 21-16, 15-10",DI,31.485579,7.267058
3,DI,803,"Deland, FL",2018-02-23,South Carolina,Katie,Smith,2,1,"24-26, 21-16, 15-10",DI,31.585579,7.267058
0,DI,803,"Deland, FL",2018-02-23,Florida State,Vanessa,Freire,2,0,"24-26, 21-16, 15-10",DI,25.831066,7.267058
1,DI,803,"Deland, FL",2018-02-23,Florida State,Brooke,Kuhlman,2,0,"24-26, 21-16, 15-10",DI,25.831066,7.267058
2,DI,803,"Deland, FL",2018-02-23,Florida State,Macy,Jerger,1,1,"21-14, 21-14",DI,32.172956,7.268023
3,DI,803,"Deland, FL",2018-02-23,Florida State,Victoria,Paranagua,1,1,"21-14, 21-14",DI,32.172956,7.268023
0,DI,803,"Deland, FL",2018-02-23,South Carolina,Ali,Denney,1,0,"21-14, 21-14",DI,26.443689,7.268023
1,DI,803,"Deland, FL",2018-02-23,South Carolina,Shannon,Williams,1,0,"21-14, 21-14",DI,26.443689,7.268023
2,DI,801,"Deland, FL",2018-02-23,Florida State,Molly,McBain,5,1,"21-10, 21-17",DI,28.158323,7.774363
3,DI,801,"Deland, FL",2018-02-23,Florida State,Eva,Torruella,5,1,"21-10, 21-17",DI,28.158323,7.774363
2,DI,801,"Deland, FL",2018-02-23,Florida State,Katie,Horton,4,1,"21-14, 21-18",DI,28.208323,7.774363
3,DI,801,"Deland, FL",2018-02-23,Florida State,Hailey,Luke,4,1,"21-14, 21-18",DI,28.208323,7.774363
2,DI,801,"Deland, FL",2018-02-23,Florida State,Francesca,Goncalves,3,1,"21-16, 21-19",DI,28.308323,7.774363
3,DI,801,"Deland, FL",2018-02-23,Florida State,Sara,Putt,3,1,"21-16, 21-19",DI,28.308323,7.774363
2,DI,801,"Deland, FL",2018-02-23,Florida State,Vanessa,Freire,2,1,"21-16, 23-21",DI,28.408323,7.774363
3,DI,801,"Deland, FL",2018-02-23,Florida State,Brooke,Kuhlman,2,1,"21-16, 23-21",DI,28.408323,7.774363
2,DI,801,"Deland, FL",2018-02-23,Florida State,Macy,Jerger,1,1,"12-21, 21-17, 15-6",DI,28.708323,7.774363
3,DI,801,"Deland, FL",2018-02-23,Florida State,Victoria,Paranagua,1,1,"12-21, 21-17, 15-6",DI,28.708323,7.774363
2,DI,800,"Deland, FL",2018-02-23,South Carolina,Hannah,Edelman,5,1,"21-15, 21-19",DI,28.158323,7.774363
3,DI,800,"Deland, FL",2018-02-23,South Carolina,Franky,Harrison,5,1,"21-15, 21-19",DI,28.158323,7.774363
2,DI,800,"Deland, FL",2018-02-23,South Carolina,Leah,Perri,4,1,"21-12, 21-15",DI,28.208323,7.774363
3,DI,800,"Deland, FL",2018-02-23,South Carolina,Macie,Tendrich,4,1,"21-12, 21-15",DI,28.208323,7.774363
2,DI,800,"Deland, FL",2018-02-23,South Carolina,Julia,Mannisto,3,1,"21-16, 21-11",DI,28.308323,7.774363
3,DI,800,"Deland, FL",2018-02-23,South Carolina,Carly,Schneider,3,1,"21-16, 21-11",DI,28.308323,7.774363
2,DI,800,"Deland, FL",2018-02-23,South Carolina,Lydia,Dimke,2,1,"21-18, 21-14",DI,28.408323,7.774363
3,DI,800,"Deland, FL",2018-02-23,South Carolina,Katie,Smith,2,1,"21-18, 21-14",DI,28.408323,7.774363
2,DI,800,"Deland, FL",2018-02-23,South Carolina,Ali,Denney,1,1,"22-24, 21-17, 15-13",DI,28.708323,7.774363
3,DI,800,"Deland, FL",2018-02-23,South Carolina,Shannon,Williams,1,1,"22-24, 21-17, 15-13",DI,28.708323,7.774363

In [84]:
df_match_history.to_csv("Data/beachvb_history.csv", encoding='utf-8')

In [85]:
df_players.to_csv("Data/beachvb_player_ratings.csv", encoding='utf-8')

In [134]:
df_agg = df_matches.groupby(['first_name', 'last_name', 'college', 'position']).agg({'position':{'position count':'count'}})
df_agg = df_matches.groupby(['first_name', 'last_name', 'college', 'position']).agg(my_agg)
g = df_agg['position'].groupby(level=0, group_keys=False)
print g.groups
#res = g.apply(lambda x: x[''],(ascending=False).head(1))
#g.nlargest(3)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)